### ISSUE TITLE
Enhancement suggestion: get the group of markers in the event when clicking a cluster

### ISSUE THREAD

**Issue by nuKle0ni** [willtemperley/v-leaflet-markercluster-parent#10]
Great addon! One thing I would like is to get a list of child markers inside the cluster when clicking on a cluster, something like:

`LMarkerClusterGroup markerCluster = new LMarkerClusterGroup();
markerCluster.addClickListener(event -> event.getChildMarkers());
`

Maybe I can try and help with this as well.

**Comment by willtemperley** [comment]
Currently you can add a click listener, but you're right, the LeafletClickEvent does not give access to the source object.  We may need a new event class to support this. I can take a look, maybe at the weekend if there's time.

**Comment by nuKle0ni** [comment]
Awesome. I have done some experiments, with new type of event like you were saying. Not working yet though, haven't done Vaadin addons before. There seems to be function already for getting the child markers, like here https://github.com/Leaflet/Leaflet.markercluster#events 

`markers.on('clusterclick', function (a) {
	// a.layer is actually a cluster
	console.log('cluster ' + a.layer.getAllChildMarkers().length);
});`

I would like to get access to those marker objects. I need to see what was grouped under that specific cluster when it was clicked. We would need to extend the LeafletClickEvent like you said.

Feel free to shoot email anton.simola@gmail.com.

**Comment by willtemperley** [comment]
This pretty much works now, needs some tidying before release. Currently an RPC is called with GeoJSON representing the marker clusters.   Take a look at MarkerClusterTestClick for usage

https://github.com/willtemperley/v-leaflet-markercluster-parent/blob/master/v-leaflet-markercluster/src/test/java/org/vaadin/addon/leaflet/demoandtestapp/MarkerClusterTestClick.java

The commit:
https://github.com/willtemperley/v-leaflet-markercluster-parent/commit/14961c974a3ff5fd26638a81e769305bfe46d6b2

**Comment by nuKle0ni** [comment]
Alright with a quick test seems to work well! I will test more today. Thanks so much, I will be checking when you make a release of this, let's see if I start using this version already. Again huge thanks for quick response.

**Comment by willtemperley** [comment]
Glad it's useful.  let me know if there are any issues / improvements needed, otherwise I'll cut a release tonight / tomorrow.  I went for GeoJSON as serialization mainly because it's well-supported by Leaflet, even if it is a bit heavyweight.

**Comment by willtemperley** [comment]
1.1.0 released in addons directory

**Comment by antonsimola** [comment]
@willtemperley Is it possible to merge this to vaadin 7 branch?

**Comment by willtemperley** [comment]
Shouldn't be too difficult. We would just need to replace the lambdas with anonymous classes and change the pom to Java7.  Feel free to create a pull request and I can release - I may not have time for a couple of weeks to do the actual coding.

**Comment by antonsimola** [comment]
#11 Pull request for Vaadin 7 cluster click event created.

**Comment by antonsimola** [comment]
Any schedule for releasing Vaadin 7 branch to Vaadin Directory? Thanks for your work!

**Comment by antonsimola** [comment]
Sorry to bug you @willtemperley, any news about the release? We would like to use this as soon as possible.

**Comment by willtemperley** [comment]
Hi sorry, been travelling a while.  I've released the version to the Vaadin Addons, thanks for doing the V7 port, good work.

**Comment by octavm** [comment]
> Currently an RPC is called with GeoJSON representing the marker clusters.

Isn't there any way how to get the actual LMarker from the marker cluster? Possibly the same LMarker instance that was added to the LMarkerClusterGroup ?

Primarily I'm interested in getting the cluster group of a marker, as indicated [here](https://github.com/Leaflet/Leaflet.markercluster#getting-the-visible-parent-of-a-marker)
