### ISSUE TITLE
Customization of Marker Cluster

### ISSUE THREAD

**Issue by AllaV** [willtemperley/v-leaflet-markercluster-parent#3]
Hi Willy,
Thank you so much for marker cluster add-on. 
It so perfectly answers our need to handle a lot of markers on the map.
But we have a strong requirement to handle differently colored markers.
I understand that underlying functionality enables to customize them.
Can you please expose some customization capability as well.
Thank you a lot again,
Alla

**Comment by RaimundBarbeln** [comment]
Is there any progress on this?
I would like to implement this myself, but i need some help how to do it

**Comment by willtemperley** [comment]
Hi, unfortunately I don't know how to do this myself either.  I believe you
need to construct the markercluster, passing a function to the constructor:

https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers

I think

**Comment by ygfuy876** [comment]
I don't know if it's the same issue: I want to use the maxClusterRadius parameter of Leaflet.markercluster
What's the way to do this from v-leaflet-markercluster?

**Comment by RaimundBarbeln** [comment]
yes, this is one of the things I would need. It seems that this is not yet implemented here.

**Comment by NitinDeshmukh** [comment]
Hi, We have added below parameterised create in MarkerClusterGroup class of  g-leaflet-markercluster:

	public static native MarkerClusterGroup create(boolean flag, int radius) 
	/*-{
	  	$wnd.alert(flag);
	  	$wnd.alert(radius);
		return new $wnd.L.MarkerClusterGroup({spiderfyOnMaxZoom: flag, maxClusterRadius: radius});
	}-*/;

Added parameterised  constructor for LMarkerClusterGroup class in v-leaflet-markercluster.

	public LMarkerClusterGroup(boolean spiderfyOnMaxZoom, int maxClusterRadius) {
		this();
		setSpiderfyOnMaxZoom(spiderfyOnMaxZoom);
		setMaxClusterRadius(maxClusterRadius);
	}
	
	public void setSpiderfyOnMaxZoom(boolean spiderfyOnMaxZoom) {
		getState().spiderfyOnMaxZoom = spiderfyOnMaxZoom;
	}
                ...



Query: v-leaflet-markercluster always calls default create() method of g-leaflet-markercluster. Is there any way we can call parameterized create method of g-leaflet-markercluster in LMarkerClusterGroup of v-leaflet-markercluster?

**Comment by normandhenault** [comment]
I have the following IVY settings with Vaadin and Eclipse : 







<dependency org="org.vaadin.addons" name="v-leaflet-markercluster" rev="0.4.5" />
I still cannot see the added functions spiderfyOnMaxZoom and setMaxClusterRadius if Itry the following :








LMarkerClusterGroup mcg = new LMarkerClusterGroup();mcg. spiderfyOnMaxZoom (function not available)mcg. setMaxClusterRadius (function not available)
Your thoughts ?
Regards
Norm.
Date: Tue, 28 Jul 2015 23:34:45 -0700

**Comment by RaimundBarbeln** [comment]
the functions Nitin mentioned are not yet committed here, because we still cant get it to work properly.

**Comment by willtemperley** [comment]
Well I finally figured out (a horrible) way to do this - pass the JS function as a string to the marker cluster group.  I tried the example in:
https://github.com/Leaflet/Leaflet.markercluster

For usage see:
https://github.com/willtemperley/v-leaflet-markercluster-parent/blob/master/v-leaflet-markercluster/src/test/java/org/vaadin/addon/leaflet/demoandtestapp/MarkerClusterTestCustomIcon.java

I simply don't think there is another way to do this.  It's horrid, JS injection like this, potentially an attack vector, but works.  The only other way would be RPC I think, e.g. a markercluster would call the RPC each time it needed to know it's state, which would create a bunch of traffic.

P.S. please post new issues in new issues, not old issues.  Apart from anything else they're much more likely to be ignored this way.
