### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by mstahv** [willtemperley/v-leaflet-markercluster-parent#8]
Hi @willtemperley,

Do you think you could find time to cut a new release to vaadin.com/directory? Our client had some issue with the add-on, but when we tried with a local build from master it worked just fine. I guess it was some of the fixes by @octavm that did it.

**Comment by willtemperley** [comment]
Hi @mstahv, sure, I'll package and upload.  I'm not really using leaflet any more, so I'm a bit lost with the versioning here - v-leaflet is on 2.0 in the directory, but 1.0.4 on github? Perhaps it would make sense to align with what you're using. Also, shall I upgrade it to Java/Vaadin 8?

**Comment by mstahv** [comment]
Yeah, 2.0 from v-leaflet is for V8. I created a pull request that updates versions used by default for V7 compatible version and then also a V8 upgrade. The webdriver test don't work properly currently, but I tested it manually. It would probably need a maven plugin that installs the driver automatically.

**Comment by willtemperley** [comment]
1.0 release uploaded to the addons directory

**Comment by mstahv** [comment]
Hi Will,

would it be still possible to build and release one version that is compatible with V7 series? That is what our customer is still needing. I guess you could fork from https://github.com/willtemperley/v-leaflet-markercluster-parent/commit/9b8b7aece973dafa573e3f34688093268d42ce52 and set the version to for example 1.0.0-v7. That would hopefully be the last V7 series release.

Thanks in advance! If there is too much trouble in it, I can also do the release package for you and then you could just upload it to the Directory?

**Comment by willtemperley** [comment]
Hi Matti,  I've assembled and uploaded a 1.0.0-v7 version to the directory, let me know if that works for you.  Cheers

**Comment by mstahv** [comment]
Awesome, looks good to me! My colleague promised to report soon how it works in production.

**Comment by tepi** [comment]
Hi, just tested this in the project and everything seems to work great! Big thanks for the release from me as well!
